@startuml
class Bullet <<sealed>> {
    + damage : float {readOnly}
    + good : bool {readOnly}
    - {static} SPEED : float
    + Bullet(good : bool, damage : float)
    + {method} Velocity : Vector2f
    + <<override>> Create() : void
    + <<override>> Update(deltaTime:float) : void
}
Entity <|-- Bullet
Scene <--- Bullet
@enduml
