@startuml
class Bullet <<sealed>> {
    + damage : float
    - good : bool
    + Bullet()
    + <<override>> Create() : void
    + <<override>> Update(scene:Scene, deltaTime:float) : void
}
Entity <|-- "0..*" Bullet
@enduml
