@startuml
class Enemy <<sealed>> {
    - health : float
    - {static} rng : Random
    + Enemy()
    + <<override>> Create() : void
    + <<override>> Update(scene:Scene, deltaTime:float) : void
}
Entity <|-- "0..*" Enemy
EventManager <--- Enemy
@enduml
