@startuml
class Enemy <<sealed>> {
    - health : float
    - {static} MAX_SPEED : float
    - {static} rng : Random {readOnly}
    + <<override>> Create() : void
    + <<override>> Destroy() : void
    - OnBeat() : void
    + <<override>> Move(deltaTime : float) : void
    + <<override>> Update(deltaTime : float) : void
}
Entity <|-- Enemy
EventManager <--- Enemy
Helpers <-- Enemy
@enduml
