@startuml
abstract class Entity {
    - textureName : string
    # sprite : Sprite
    # velocity : Vector2f
    + Entity(textureName:string)
    + {method} Dead : bool
    + {method} Position : Vector2f
    + {method} <<virtual>> Bounds : FloatRect {readOnly}
    + <<virtual>> Create() : void
    + <<virtual>> Destroy() : void
    + <<virtual>> Move(deltaTime : float) : void
    + <<abstract>> Update(deltaTime : float) : void
    + <<virtual>> Render(window : RenderWindow) : void
}
AssetManager <- Entity
@enduml
