@startuml
class EventManager <<static>> {
    + {static} FireBullet : BulletEvent
    + {static} StruckBeat : DamageEvent
    + {static} Beat : Action
    + {static} DecreaseHealth : HealthEvent
    + {static} PublishFireBullet(source : Entity, damage : float) : void
    + {static} PublishStruckBeat(damage : float) : void
    + {static} PublishBeat() : void
    + {static} PublishDecreaseHealth(damage : int) : void
}
@enduml
