@startuml
class GUI <<sealed>> {
    - menuSelection : int
    - font : Font {readOnly}
    - ui : Text {readOnly}
    + Update() : void
    + Render(window:RenderWindow) : void
}
GUI -> InputManager
GUI -> EventManager
GUI -> Scene
@enduml
