@startuml
class Player <<sealed>> {
    - {static} STEERING_FORCE : float
    - {static} MAX_SPEED : float
    - {static} MAX_GRACE : float
    - grace : float
    - guns : Vector2f[]
    + {method} Guns : Vector2f[]
    + Create() : void
    + Destroy() : void
    - OnStruckBeat(damage : float) : void
    + <<override>> Move(deltaTime : float) : void
    + <<override>> Update(deltaTime : float) : void
}
Entity <|-- Player
InputManager <--- Player
UserActions <--- Player
Helpers <-- Player
EventManager <--- Player
@enduml
