@startuml
class RythmManager <<sealed>> {
    - beatTimer : float
    - music : Music
    - {static} MAX_BEAT_TIME : float
    + Update(deltaTime : float) : void
    + Pause() : void
    + Play() : void
}
InputManager <-- RythmManager
UserActions <-- RythmManager
EventManager <-- RythmManager
@enduml
