@startuml
class RythmManager <<sealed>> {
    - songTime : Clock
    - {static} MAX_BEAT_TIME : float
    + Update(deltaTime : float) : void
}
InputManager <-- RythmManager
UserActions <-- RythmManager
EventManager <-- RythmManager
@enduml
